# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vw-dXykXBg50YWpA1yHQaLOSzUI0yNwr

IMPORT LIBRARY
"""

from sklearn import datasets

"""LOAD DATASET"""

diabetes = datasets.load_diabetes()

diabetes

"""DESC OF THE DIABETES DATASETS"""

print(diabetes.DESCR)

"""FEATURES NAME"""

print(diabetes.feature_names)

"""CREATE X AND Y DATA METRICS"""

x = diabetes.data
y = diabetes.target

x.shape , y.shape

"""IMPORT LIB

"""

from sklearn.model_selection import train_test_split

"""80/20 DATA SPLIT"""

x_train ,x_test,y_train , y_test = train_test_split(x,y, test_size = 0.2)

x_train.shape, x_test.shape ,y_train.shape,y_test.shape

"""LINEAR REGRESSION MODEL"""

from sklearn import linear_model
from sklearn.metrics import mean_squared_error,r2_score

"""DEFINE THE REG MODEL"""

model = linear_model.LinearRegression()

"""BUILD TRANING MODEL"""

model.fit(x_train,y_train)

"""APPLIED TRAINED MODEL TO MAKE PREDICTION"""

y_pred = model.predict(x_test)

"""RESULT

"""

print("mse is:", mean_squared_error(y_test,y_pred))

print("coefficient of determination:", r2_score(y_test,y_pred))

"""scatter plots"""

import seaborn as sns
import matplotlib.pyplot as plt

y_test

y_pred

sns.scatterplot(x=y_test, y=y_pred ,color='blue', label='Data points')